key_name = 'ironcheese'  # Name of the key pair to add to new instances.
ssh_key = 'ironcheese.pem'  # Path to corresponding SSH private key.
security_group = 'chazz'  # A security group that allows SSH.
default_ami = 'v1.0.0'  # The AMI name to connect to and create.
aws_region = 'us-west-2'  # The Oregon region.
ec2_type = 'f1.2xlarge'  # Launch the smallest kind of F1 instance.
user = 'centos'  # The user for SSH connections.

# Mapping from version names to image IDs.
[ami_ids]
'v1.0.0'   = 'ami-0c6849749f4551621'
'v0.5.2'   = 'ami-0efe7628e32d547ae'
'v0.5.1'   = 'ami-0ed2d075e7a3482ca'
'v0.4.2'   = 'ami-0ebfadb08765d6ddf'
'20190511' = 'ami-0e1d91c72cabb5b3f'
'20190510' = 'ami-0343798c9b9136e4e'
'20190417' = 'ami-0270f06e16bfee050'
'20190405' = 'ami-0ce51e94bbeba2650'
'20190319' = 'ami-0c7ccefee8f931530'
