[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "chazz"
author = "Adrian Sampson"
author-email = "asampson@cs.cornell.edu"
requires = [
    "click",
    "boto3",
    "click-log",
    "tomlkit",
]

[tool.flit.scripts]
chazz = "chazz:chazz"
