#include "f1_helper.h"
#include <stdlib.h>

// 4 x 4 - 4 ( the t p row, in charge of io ) 
#define X1 0
#define Y1 1
#define X2 4
#define Y2 4
#define NUM_TILES (X2 - X1) * (Y2 - Y1)

void print_vector(int* v, int start, int length) {
  for (int i = start; i < start + length; i++) {
    int val = v[i];
    if (i == start) {
        printf("(%d, ", val);
        fflush(stdout);
    }
    else if (i == start + length - 1) {
        printf(" %d)\n", val);
        fflush(stdout);
    }
    else {
        printf("%d, ", val);
        fflush(stdout);
    }
  }
}

int main(int argc, char *argv[]) {
  assert(argc == 2);
  char *manycore_program = argv[1];
  
  // Initialize and get userspace pointer to FPGA
  uint8_t fd;
  if (hb_mc_init_host(&fd) != HB_MC_SUCCESS) {
    printf("failed to initialize host.\n");
    return 0;
  }
 
  // Load SPMD program in each core 
  hammaLoadMultiple(fd, manycore_program, X1, Y1, X2, Y2);
    
  // Define randomly generated vectors A, B,
  // with entries in [0, 100]
  int dim = 120;
  int *h_src0 = (int*)malloc(dim * sizeof(int));
  for(int i = 0; i < dim; i++) {
    h_src0[i] = rand() % 100;
  }
  int *h_src1 = (int*)malloc(dim * sizeof(int));
  for(int i = 0; i < dim; i++) {
    h_src1[i] = rand() % 100;
  }

  // Print generated vectors A, B
  printf("Input vectors: \n");
  printf("A = ");
  print_vector(h_src0, 0, dim);

  printf("B = ");
  print_vector(h_src1, 0, dim);
   
  // Load slice of vectors A, B to each tile
  int num_cores = (X2 - X1) * (Y2 - Y1);
  int dim_per_core = dim / num_cores;
  for (int y = Y1; y < Y2; y++) {
    for (int x = X1; x < X2; x++) {
      // This offset slices vectors across cores 
      // in column-major order
      int offset = (y-Y1) * (X2-X1) * dim_per_core + 
                   (x-X1) * dim_per_core;

      hammaSymbolMemcpy(fd, x, y, manycore_program, "g_src1", 
                        (void*)(h_src0 + offset), 
                        dim_per_core * sizeof(int), 
                        hostToDevice);
      hammaSymbolMemcpy(fd, x, y, manycore_program, "g_src0", 
                        (void*)(h_src1 + offset), 
                        dim_per_core * sizeof(int), 
                        hostToDevice);

      // print out slices sent to core (x, y)
      printf("Slice of vector A sent to core (%d, %d) = ", x, y);
      print_vector(h_src0, offset, dim_per_core);

      printf("Slice of vector B sent to core (%d, %d) = ", x, y);
      print_vector(h_src1, offset, dim_per_core);
    }
  }

  // Run all of the tiles
  hammaRunMultiple(fd, X1, Y1, X2, Y2);


  // Collect results from each tile
  int *h_dest = (int*)malloc(dim * sizeof(int));
  for (int y = Y1; y < Y2; y++) {
    for (int x = X1; x < X2; x++) {
      int offset = (y-Y1)*(X2-X1)*dim_per_core + (x-X1) * dim_per_core;
      hammaSymbolMemcpy(fd, x, y, manycore_program, "g_dest",
                        (void*)(h_dest + offset),
                        dim_per_core * sizeof(int),
                        deviceToHost);

      // print out results generated by core (x, y)
      printf("Output at core (%d, %d) = ", x, y);
      print_vector(h_dest, offset, dim_per_core);
    }
  }

  // Verify correctness of results
  int success = 1;
  for (int i = 0; i < dim; i++) {
    int correct_val = h_src0[i] + h_src1[i];
    if (h_dest[i] != correct_val) {
      printf("\nLOGIC ERROR: expected %d at index %d, got %d\n", 2*i, i, h_dest[i]);
      printf("\n");
      fflush(stdout);
      success = 0;
    }
  }
  if(success) {
    printf("VVADD yields correct answer.\n");
    printf("\n");
    fflush(stdout);
  }
      
  // cleanup host
  return 0;
}
